spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: spring
    password: test2019
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 1000
      idle-timeout: 10000
      max-lifetime: 30000
