apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mypets
  name: mypets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypets
  template:
    metadata:
      labels:
        app: mypets
    spec:
      containers:
      - image: gcr.io/cf-sandbox-trisberg/mypets:mongodb
        imagePullPolicy: Always
        name: mypets
        env:
          - name: SPRING_CLOUD_KUBERNETES_CONFIG_PATHS
            value: /config/config.yaml
          - name: SPRING_DATA_MONGODB_PASSWORD
            valueFrom:
               secretKeyRef:
                 name: mypets-mongodb
                 key: mongodb-password
        volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: mypets
          items:
          - key: application.yaml
            path: config.yaml
