---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "mypets"
    version: "0.0.1-refresh"
  name: "mypets"
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 8080
  selector:
    app: "mypets"
    version: "0.0.1-refresh"
  type: "LoadBalancer"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "mypets"
    version: "0.0.1-refresh"
  name: "mypets"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mypets"
      version: "0.0.1-refresh"
  template:
    metadata:
      labels:
        app: "mypets"
        version: "0.0.1-refresh"
    spec:
      containers:
      - name: "app"
        image: "springdeveloper/mypets:0.0.1-refresh"
        imagePullPolicy: "Always"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: refresh
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        livenessProbe:
          httpGet:
            path: "/actuator/health"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: "/actuator/health"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 10
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: mypets-refresh
          items:
          - key: application.yaml
            path: application-refresh.yaml
