---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "mypets"
    version: "0.0.1-SNAPSHOT"
  name: "mypets"
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 8080
  selector:
    app: "mypets"
    version: "0.0.1-SNAPSHOT"
  type: "LoadBalancer"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    service.projectriff.io/binding-type: "spring-boot"
    service.projectriff.io/binding-secrets: "mypets-credentials"
  labels:
    app: "mypets"
    version: "0.0.1-SNAPSHOT"
  name: "mypets"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mypets"
      version: "0.0.1-SNAPSHOT"
  template:
    metadata:
      labels:
        app: "mypets"
        version: "0.0.1-SNAPSHOT"
    spec:
      containers:
      - name: "app"
        image: "trisberg/mypets:0.0.1-SNAPSHOT"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        livenessProbe:
          httpGet:
            path: "/actuator/health"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: "/actuator/health"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          timeoutSeconds: 10
