apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mypets-refresh
stringData:
  application.yaml: |-
    spring:
      datasource:
        url: jdbc:mysql://mypets-mysql.default.svc.cluster.local:3306/mypets
        username: riff
        password: test2019
        hikari:
          minimum-idle: 2
          maximum-pool-size: 5
          connection-timeout: 1000
          idle-timeout: 10000
          max-lifetime: 30000
